@startuml
actor User
User->landingPage
landingPage->(show login form)
(show login form)->(check registered user)
(show login form)->(check password)
User-->(create profile)
User-->(edit profile)
User-->(show add new vehicle form):click \nadd new button

User-->(edit vehicle)
User--->(logout)


@enduml